package com.flab.ticketing.order.enums

import org.springframework.http.HttpStatus

enum class TossPayErrorCode(
    val responseStatus: HttpStatus
) {
    ALREADY_PROCESSED_PAYMENT(HttpStatus.BAD_REQUEST),
    PROVIDER_ERROR(HttpStatus.BAD_REQUEST),
    EXCEED_MAX_CARD_INSTALLMENT_PLAN(HttpStatus.BAD_REQUEST),
    INVALID_REQUEST(HttpStatus.BAD_REQUEST),
    NOT_ALLOWED_POINT_USE(HttpStatus.BAD_REQUEST),
    INVALID_REJECT_CARD(HttpStatus.BAD_REQUEST),
    BELOW_MINIMUM_AMOUNT(HttpStatus.BAD_REQUEST),
    INVALID_CARD_EXPIRATION(HttpStatus.BAD_REQUEST),
    INVALID_STOPPED_CARD(HttpStatus.BAD_REQUEST),
    EXCEED_MAX_DAILY_PAYMENT_COUNT(HttpStatus.BAD_REQUEST),
    NOT_SUPPORTED_INSTALLMENT_PLAN_CARD_OR_MERCHANT(HttpStatus.BAD_REQUEST),
    INVALID_CARD_INSTALLMENT_PLAN(HttpStatus.BAD_REQUEST),
    NOT_SUPPORTED_MONTHLY_INSTALLMENT_PLAN(HttpStatus.BAD_REQUEST),
    EXCEED_MAX_PAYMENT_AMOUNT(HttpStatus.BAD_REQUEST),
    INVALID_CARD_LOST_OR_STOLEN(HttpStatus.BAD_REQUEST),
    RESTRICTED_TRANSFER_ACCOUNT(HttpStatus.BAD_REQUEST),
    INVALID_CARD_NUMBER(HttpStatus.BAD_REQUEST),
    NOT_REGISTERED_BUSINESS(HttpStatus.BAD_REQUEST),
    EXCEED_MAX_ONE_DAY_WITHDRAW_AMOUNT(HttpStatus.BAD_REQUEST),
    EXCEED_MAX_ONE_TIME_WITHDRAW_AMOUNT(HttpStatus.BAD_REQUEST),
    EXCEED_MAX_AMOUNT(HttpStatus.BAD_REQUEST),
    INVALID_ACCOUNT_INFO_RE_REGISTER(HttpStatus.BAD_REQUEST),
    NOT_AVAILABLE_PAYMENT(HttpStatus.BAD_REQUEST),
    UNAPPROVED_ORDER_ID(HttpStatus.BAD_REQUEST),
    EXCEED_MAX_MONTHLY_PAYMENT_AMOUNT(HttpStatus.BAD_REQUEST),

    INVALID_AUTHORIZE_AUTH(HttpStatus.UNAUTHORIZED),

    REJECT_ACCOUNT_PAYMENT(HttpStatus.FORBIDDEN),
    REJECT_CARD_PAYMENT(HttpStatus.FORBIDDEN),
    REJECT_CARD_COMPANY(HttpStatus.FORBIDDEN),
    FORBIDDEN_REQUEST(HttpStatus.FORBIDDEN),
    REJECT_TOSSPAY_INVALID_ACCOUNT(HttpStatus.FORBIDDEN),
    EXCEED_MAX_AUTH_COUNT(HttpStatus.FORBIDDEN),
    EXCEED_MAX_ONE_DAY_AMOUNT(HttpStatus.FORBIDDEN),
    NOT_AVAILABLE_BANK(HttpStatus.FORBIDDEN),
    INVALID_PASSWORD(HttpStatus.FORBIDDEN),
    FDS_ERROR(HttpStatus.FORBIDDEN),


    NOT_FOUND_PAYMENT(HttpStatus.NOT_FOUND),
    NOT_FOUND_PAYMENT_SESSION(HttpStatus.NOT_FOUND),


    INVALID_API_KEY(HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_UNREGISTERED_SUBMALL(HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHORIZED_KEY(HttpStatus.INTERNAL_SERVER_ERROR),
    INCORRECT_BASIC_AUTH_FORMAT(HttpStatus.INTERNAL_SERVER_ERROR),
    UNKNOWN_TOSS_MESSAGE(HttpStatus.INTERNAL_SERVER_ERROR),


    NOT_FOUND_TERMINAL_ID(HttpStatus.BAD_GATEWAY),
    CARD_PROCESSING_ERROR(HttpStatus.BAD_GATEWAY),
    FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING(HttpStatus.BAD_GATEWAY),
    FAILED_INTERNAL_SYSTEM_PROCESSING(HttpStatus.BAD_GATEWAY),
    UNKNOWN_PAYMENT_ERROR(HttpStatus.BAD_GATEWAY)

}