package com.flab.ticketing.order.enums

import org.springframework.http.HttpStatus

enum class TossPayCancelErrorCode(
   override val responseStatus: HttpStatus
): TossPayErrorCode{

    ALREADY_CANCELED_PAYMENT(HttpStatus.BAD_REQUEST),
    INVALID_REFUND_ACCOUNT_INFO(HttpStatus.BAD_REQUEST),
    EXCEED_CANCEL_AMOUNT_DISCOUNT_AMOUNT(HttpStatus.BAD_REQUEST),
    INVALID_REQUEST(HttpStatus.BAD_REQUEST),
    INVALID_REFUND_ACCOUNT_NUMBER(HttpStatus.BAD_REQUEST),
    INVALID_BANK(HttpStatus.BAD_REQUEST),
    NOT_MATCHES_REFUNDABLE_AMOUNT(HttpStatus.BAD_REQUEST),
    PROVIDER_ERROR(HttpStatus.BAD_REQUEST),
    REFUND_REJECTED(HttpStatus.BAD_REQUEST),
    ALREADY_REFUND_PAYMENT(HttpStatus.BAD_REQUEST),
    FORBIDDEN_BANK_REFUND_REQUEST(HttpStatus.BAD_REQUEST),

    NOT_CANCELABLE_AMOUNT(HttpStatus.FORBIDDEN),
    EXCEED_MAX_REFUND_DUE(HttpStatus.FORBIDDEN),
    NOT_ALLOWED_PARTIAL_REFUND_WAITING_DEPOSIT(HttpStatus.FORBIDDEN),
    NOT_ALLOWED_PARTIAL_REFUND(HttpStatus.FORBIDDEN),
    NOT_AVAILABLE_BANK(HttpStatus.FORBIDDEN),

    NOT_FOUND_PAYMENT(HttpStatus.NOT_FOUND),


    INCORRECT_BASIC_AUTH_FORMAT(HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHORIZED_KEY(HttpStatus.INTERNAL_SERVER_ERROR),

    FAILED_INTERNAL_SYSTEM_PROCESSING(HttpStatus.BAD_GATEWAY),
    FAILED_REFUND_PROCESS(HttpStatus.BAD_GATEWAY),
    FAILED_METHOD_HANDLING_CANCEL(HttpStatus.BAD_GATEWAY),
    FAILED_PARTIAL_REFUND(HttpStatus.BAD_GATEWAY),
    COMMON_ERROR(HttpStatus.BAD_GATEWAY),
    FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING(HttpStatus.BAD_GATEWAY)
}