spring:
  application:
    name: min-ticketing
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  web:
    resources:
      add-mappings: false
  mail:
    sender: ${MAIL_SENDER}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    elasticsearch:
      repositories:
        enabled: true
      url: ${ES_HOST}
      api-key: ${ES_API_KEY}
server:
  port: 443
  ssl:
    key-store: ${KEYSTORE_PATH}
    key-store-type: PKCS12
    key-store-password: ${KEYSTORE_PASSWORD}
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: ${SERVER_THREAD_MAX_SIZE:200}
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token:
    time: ${ACCESS_TOKEN_ALIVE_TIME}

service:
  url: https://minturtle.kro.kr
  toss:
    url: https://api.tosspayments.com
    confirm-uri: /v1/payments/confirm
    cancel-uri: /v1/payments/%s/cancel
    access-token: ${TOSS_ACCESS_TOKEN}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{36}] - %msg%n"
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, prometheus


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
cors:
  origins: ${CORS_ORIGINS}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ticketing?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    sender: noreply@minticketing.com
    host: smtp.gmail.com
    port: 465
    username: asdas
    password: 21312asf
  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200
  web:
    resources:
      add-mappings: false
server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

jwt:
  secret: UshUVcHhZ8olLFeQVCnjoRjp1EjY8vRY6UUR12QKCWDh8LcJFmPrrxRYSQSdZZVc

  access-token:
    time: 1000000

service:
  url: http://localhost
  toss:
    url: https://api.tosspayments.com
    confirm-uri: /v1/payments/confirm
    cancel-uri: /v1/payments/%s/cancel
    access-token: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6 # Toss Payments 임시 키

logging:
  pattern:
    console: "%msg%n"


management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

cors:
  origins: http://localhost:3000