spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    sender: ${MAIL_SENDER}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token:
    time: ${ACCESS_TOKEN_ALIVE_TIME}

service:
  url: https://minturtle.kro.kr
  toss:
    url: https://api.tosspayments.com/
    confirm-uri: /v1/payments/confirm
    cancel-uri: /v1/payments/%s/cancel
    access-token: ${TOSS_ACCESS_TOKEN}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{36}] - %msg%n"
  file:
    name: ticketing
    path: /app/logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 30