name: AI Code Review

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Code Review Bot
        uses: careersupport-org/code-review-bot@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          career-support-api-token: ${{ secrets.CAREER_SUPPORT_API_TOKEN }}
          repository-name: ${{ github.repository }}
          pr-number: ${{ github.event.pull_request.number }}