name: Jacoco Test Coverage Analyze

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew testCoverage

      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: Jacoco Test Coverage
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
          fail-on-coverage-error: false

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-reports
          path: |
            **/build/reports/jacoco/
            **/build/reports/tests/

      - name: Create Coverage Comment
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Jacoco Test Coverage Report
            
            Overall coverage: ${{ steps.jacoco.outputs.coverage-overall }}%
            Changed files coverage: ${{ steps.jacoco.outputs.coverage-changed-files }}%
            
            [Full report](${{ steps.jacoco.outputs.report-url }})
            
            Coverage reports have been uploaded as artifacts. You can download them from the Actions tab.`
            })